target:
	@javac ./Command.java
	@javac ./Light.java
	@javac ./Stereo.java
	@javac ./LightOnCommand.java
	@javac ./LightOffCommand.java
	@javac ./StereoOnWithCDCommand.java
	@javac ./StereoOffCommand.java
	@javac ./RemoteControl.java
	@javac ./RemoteLoader.java

	@java RemoteLoader

	@rm ./*.class
