target:
	@javac ./Observer.java
	@javac ./Subject.java
	@javac ./DisplayElement.java
	@javac ./CurrentConditionDisplay.java
	@javac ./StatisticsDisplay.java
	@javac ./WeatherData.java
	@javac ./WeatherStation.java

	@java WeatherStation

	@rm ./*.class
