target:
	@javac ./Pizza.java
	@javac ./PizzaStore.java
	@javac ./NewYorkPizzaStore.java
	@javac ./NewYorkStylePizza.java
	@javac ./NewYorkStyleCheesePizza.java
	@javac ./NewYorkStyleVeggiePizza.java
	@javac ./PizzaTest.java

	@java PizzaTest

	@rm *.class
