target:
	@javac ./Beverage.java
	@javac ./CondimentDecorator.java
	@javac ./Mocha.java
	@javac ./Whip.java
	@javac ./Soy.java
	@javac ./Espresso.java
	@javac ./StarbuzzCoffee.java

	@java StarbuzzCoffee
	@rm *.class
